### ISSUE TITLE
SSR state hydration

### ISSUE THREAD

**Issue by tim-smart** [felangel/bloc.js#5]
Thanks for doing a Javascript fork! Had a crack at it myself (https://github.com/tim-smart/bloc-js) but would be great to switch to a project that has a bigger community behind it (and I don't want to maintain it lol).

It would be awesome if you could support state hydration with this library, as it would help with creating apps that make use of Server-Side-Rendering. This is a non-issue with Flutter obviously, which will probably mean a different API to the Dart equivalent.

Here is a Next.js example https://github.com/tim-smart/nextjs-bloc-js-example

Let me know what you think!

**Comment by felangel** [comment]
Hi @tim-smart 👋 
Thanks for opening an issue!

I think it's a great idea 👍I'm currently focusing on several issues in the Dart Bloc repo but if you have some time and are willing to open a PR that would be awesome 😄 

If not, I'll probably get to this sometime next week because I also have to update the bloc.js API to align with the new 1.0.0 changes in the Dart Bloc API. Let me know if you're able to contribute and thanks for bringing this up! 💯

**Comment by tim-smart** [comment]
I have make changes the way it works - quite different to before.
No longer using a stream of events to cut down on boilerplate and simplify the API.

So I'm going to close this!

**Comment by Tokenyet** [comment]
Hey, A lover of flutter and bloc here! Want to share some experience with this project. This project is working as expected, but need some React.Context API to be work as `BlocProvider`. It's all fine with SPA, but when I used Nextjs + Bloc.js, and what some SSR feature. Bloc became a bad monster, because of the page should be rendered on server, and passed to client, Bloc has no way to sync data :( There is such a obstacle I experienced.

By the way, I still love to use bloc with flutter, and maybe SPA. but for Nextjs(SSR), I think I should go traditional redux way, the idea of store is easy for sync data on client and server, although I hate the flow of redux 😝
